RUN groupadd -r work && useradd -r -g work work

USER work

ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS \
    JHIPSTER_SLEEP=0 \
    JAVA_OPTS=""

CMD echo "The application will start in ${JHIPSTER_SLEEP}s..." && \
    sleep ${JHIPSTER_SLEEP} && \
    java ${JAVA_OPTS} -Djava.security.egd=file:F:\springboot-springsecurity-jwt-demo -jar /app.war

EXPOSE 8080

ADD *.war app.war
